import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { db } from '@/lib/db'
import {  auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang="en">
          <head>
        <meta name="google-site-verification" content="wHIxtQ2Ehw-Z4mysz4nMFthsRdGwaCmbnp72t9r7mkI" />
       </head>
    
        <body className={inter.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
